CREATE TABLE IF NOT EXISTS hits (id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, tag TEXT, country TEXT, region TEXT, city TEXT, ref TEXT, ua TEXT);
CREATE TABLE IF NOT EXISTS signups (id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT NOT NULL, event TEXT NOT NULL, email TEXT NOT NULL, country TEXT, UNIQUE(event, email));
